# Generated by Django 6.1.1 on 2026-09-07 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huntSessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hunt',
            old_name='hunt_Id',
            new_name='hunt_id',
        ),
    ]
