# Generated by Django 6.1.1 on 2026-09-07 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huntSessions', '0002_rename_hunt_id_hunt_hunt_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hunt',
            old_name='hunt_Name',
            new_name='hunt_name',
        ),
    ]
