# Generated by Django 6.1.1 on 2026-09-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntSessions', '0003_rename_hunt_name_hunt_hunt_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('question_type', models.CharField(choices=[('multiple choice', 'Multiple Choice'), ('short answer', 'Short Answer'), ('picture', 'Picture Submission')], max_length=50)),
            ],
        ),
    ]
