# Generated by Django 6.1.1 on 2026-09-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntSessions', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='questions',
            field=models.ManyToManyField(to='huntSessions.question'),
        ),
    ]
