# Generated by Django 6.1.1 on 2026-09-11 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntSessions', '0005_hunt_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple choice', 'Multiple Choice'), ('short answer', 'Short Answer'), ('picture', 'Picture Submission')], max_length=25),
        ),
        migrations.CreateModel(
            name='HuntSession',
            fields=[
                ('Session_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('finished', 'Finished')], max_length=20)),
                ('join_code', models.CharField(max_length=6, unique=True)),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huntSessions', to='huntSessions.hunt')),
            ],
        ),
    ]
