# Generated by Django 6.1.1 on 2026-09-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntSessions', '0006_alter_question_question_type_huntsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunt',
            name='location',
            field=models.CharField(choices=[('joondalup', 'Joondalup'), ('bunburry', 'Bunbury'), ('city campus', 'City Campus')], max_length=50),
        ),
    ]
