# Generated by Django 6.1.1 on 2026-09-13 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntSessions', '0007_alter_hunt_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunt',
            name='location',
            field=models.CharField(choices=[('Joondalup', 'Joondalup'), ('Bunburry', 'Bunbury'), ('City Campus', 'City Campus')], max_length=50),
        ),
        migrations.AlterField(
            model_name='huntsession',
            name='hunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunt_sessions', to='huntSessions.hunt'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='huntSessions.huntsession')),
            ],
        ),
    ]
