# Generated by Django 6.1.1 on 2026-09-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huntSessions', '0008_alter_hunt_location_alter_huntsession_hunt_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
